### PR TITLE
Implemented Debug for Stream and fixed a few clippy lints

### PR DESCRIPTION
**Pull request by Kixiron**
* Implemented `Debug` for `Stream` (and will implement `Debug` for `Arranged` and `Collection` after this lands), this allows for unwrapping on items that hold streams, as an example `Vec<Stream>::try_into().unwrap()` would previously error and force you to use `.unwrap_or_else(|_| panic!())`, this allows it to happen seamlessly. Just a nice little quality of life tweak
* Fixed a few clippy lints, there seems to be quite a lot so if it's ok with you I can make a follow-up that fixes more of them

### CODE REVIEW

**Comment by frankmcsherry** [comment]
Thanks! Just to nip things in the bud, clippy and I disagree a lot! Lemme take a look before you sink too much time, as several classes of its lints are imo antipatterns. Some are great, but .. not all. :)

**Comment by Kixiron** [comment]
Any updates on this?

**Comment by frankmcsherry** [comment]
Yes, as we discussed on the community Slack, the clippy lint fixes are going to hold up the PR. If you'd like to go for just the `Debug` implementation that is great! And, if at all possible minimum `cargo fmt` line noise.

**Comment by Kixiron** [comment]
Sure, can do!

**Comment by frankmcsherry** [comment]
Looks great!

**Pull request merged**
