### PR TITLE
Fix broken links to simple example

### PR DESCRIPTION
**Pull request by astubbs**
I don't know if you want to change all the references in the book to add the `timely/` prefix or not, but I think the link in the readme should be updated ;)

### CODE REVIEW

**Comment by astubbs** [comment]
Let me know which you want and I'll adjust..

**Comment by frankmcsherry** [comment]
Sorry for the delay on this! These look great, and I appreciate the effort of submitting them as a PR!

**Comment by astubbs** [comment]
No worries! But do you want to update all the links in the book? They're all missing the same sub dir.

**Comment by frankmcsherry** [comment]
It occurred to me that you offered to do even more just after I merged, and I didn't want to walk back the good vibes of merging with a request like that. :)

If you are up for link-fixing, that would be amazing. It's not glamorous work, and I can eventually get to it, but if you happen to be grinding through the text with less bleary eyes than I would have that works especially well for me. ;)

**Comment by astubbs** [comment]
Yeah man no worries, I'll take a stab. Just wasn't sure if you
actually wanted to insert the examples prefix into the plain text
links in the book, because it's a bit redundant (i.e. prefix: example
code can be found under the examples folder)...

**Comment by frankmcsherry** [comment]
I think just fixing up the links should be fine. Tbh I'm not sure; I don't have a great read on the expectations of a new reader arriving for the first time; if you have thoughts here I would trust them!

**Pull request merged**
