### PR TITLE
Fix build deprecation warnings

### PR DESCRIPTION
**Pull request by max-sixty**
Just running `cargo fix`

### CODE REVIEW

**Comment by max-sixty** [comment]
I'm trying to explore more on the code - would you take a PR fixing clippy lints too?

**Comment by frankmcsherry** [comment]
Hello!

Thanks for the PR. It looks great, I'm up for merging it, but generally no clippy PRs are not great. It has a few too many opinions about things, and we disagree on many of them. If there are stylistic things getting in your way, let me know and I can look into them.

**Comment by frankmcsherry** [comment]
Merging, but not attempting to terminate discussion, just want to land this stuff.

**Comment by max-sixty** [comment]
Great!

**Pull request merged**
